name: Lint and Test Python Code Base

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/*.py'
      - 'requirements.txt'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**/*.py'
      - 'requirements.txt'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Install Dependencies
        run: |
          pip install -r requirements-dev.txt
      - name: Lint and Check Formatting
        run: |
          echo "Running flake8 and black"
          flake8 .
          black --check .
          isort --check-only .

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Tests with Coverage
        working-directory: src
        run: |
          pip install coverage
          coverage run --branch --omit=manage.py,test*.py manage.py test
          # generate coverage report
          coverage report -m --skip-covered --skip-empty --fail-under 69
          # write report to xml data
          coverage xml --skip-empty -o coverage.xml
      - name: Get Cover
        uses: orgoro/coverage@v3.2
        if: ${{ github.event_name == 'pull_request' }}
        with:
            coverageFile: src/coverage.xml
            thresholdAll: 0.69
            token: ${{ secrets.GITHUB_TOKEN }}
